### ISSUE TITLE
Paris - Candelaria

### ISSUE THREAD

**Issue by mnot** [CocktailStandards/CocktailStandards.github.io#28]
https://www.yelp.com/biz/candelaria-paris-2

From Dandelyan waitress

**Comment by hober** [comment]
FWIW this is the best Mexican food I've had in Paris. I can't speak to the tequila/mezcal selection in the speakeasy out back as tequila and I had a falling out in college, and are no longer on speaking terms.

**Comment by mnot** [comment]
@martinthomson and I went last week. One drink was really amazing, the rest were good but not knock-it-out-of-the-park great. Little Red Door was a clear cut above (although we'd had more to drink by then :)
