### ISSUE TITLE
Paris - Sherry Butt

### ISSUE THREAD

**Issue by mnot** [CocktailStandards/CocktailStandards.github.io#30]
http://www.sherrybuttparis.com

**Comment by mnot** [comment]
Nice enough drinks, but the waitress charged my card for 335 Euro instead of 35, and said "this is the first time this has happened" when I pointed it out. Right.

**Comment by hober** [comment]
Ugh, I'm really sorry to hear that. I love that place, and have been going since shortly after they opened.
